version: "3.0"

services:
  backend:
    container_name: back_freelance
    build:
      dockerfile: Dockerfile
      context: ./apps/backend
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  frontend:
    container_name: front-freelance
    build:
      dockerfile: Dockerfile
      context: ./apps/frontend
    env_file:
      - .development.env
    volumes:
      - /app/node_modules
      - ./client:/app
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .development.env
    environment:
      POSTGRES_DB: freelance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qweqwe
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
